require("theme/onedark")
require("theme/dashboard")
require("theme/lualine")
require("theme/highlights/generic")
require("theme/highlights/diagnostics")
require("theme/highlights/dashboard")
require("theme/highlights/gitsigns")
