# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000

# Sets user-defined palette
# Palettes must be defined _after_ this line
palette = "rose-pine-moon"

# Starship modules
[character]
success_symbol = "[[➜](leaf)](leaf)"
error_symbol = "[[➜](love)](love)"
vimcmd_symbol = "[➜](overlay)" # For use with zsh-vi-mode

[git_branch]
style = "bold iris"

[git_status]
style = "bold iris"

[directory]
truncation_length = 4
style = "bold pine"

# Palette definitions
[palettes.rose-pine-moon]
overlay = '#393552'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ea9a97'
pine = '#3e8fb0'
foam = '#9ccfd8'
iris = '#c4a7e7'
leaf = '#95b1ac'
