#!/usr/bin/env sh

## General setings
yabai -m config window_shadow off
yabai -m config mouse_follows_focus off

## Change how yabai looks
yabai -m config layout bsp
yabai -m config top_padding 0
yabai -m config bottom_padding 0
yabai -m config left_padding 0
yabai -m config right_padding 0
yabai -m config window_gap 10

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^Preview$" manage=off
yabai -m rule --add app="^CatoClient$" manage=off
yabai -m rule --add app="^Cisco AnyConnect Secure Mobility Client$" manage=off
yabai -m rule --add app="^Calculator$" manage=off

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child
yabai -m config window_topmost off

# yabai -m config window_opacity off
# yabai -m config window_opacity_duration 0.00
# yabai -m config active_window_opacity 1.0

## some other settings
yabai -m config split_ratio 0.50

# # set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier ctrl

# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize

# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move

echo "yabai configuration loaded.."
